/** Configuración central del juego — misiones, tienda, asedios */
const shopCatalog = require('./shop-catalog');

module.exports = {
  STARTER_TERRITORY_PIXELS: 300,
  STARTER_COINS: 50,
  SIEGE_COST: 75,
  SIEGE_DURATION_MS: 15 * 60 * 1000,
  SIEGE_CAPTURE_PERCENT: 40,
  SIEGE_COOLDOWN_MS: 30 * 60 * 1000,
  GADGET_BRUSH_CORRIDO: 'brush_corrido',
  BRUSH_CORRIDO_PRICE: 450,
  CLICK_ONLY_PAINT_MS: 280,
  CHISEL_SAME_PIXEL_MS: 60,

  /** Tycoon: empiezas con 10 clics por celda vacía; mejoras hasta 1 clic */
  TYCOON_START_CLICKS: 10,
  TYCOON_MIN_CLICKS: 1,
  TYCOON_COMBO_WINDOW_MS: 1600,
  TYCOON_XP_PER_TAP: 1,
  TYCOON_XP_PER_PIXEL: 8,
  TYCOON_COINS_PER_PIXEL: 2,
  TYCOON_LEVEL_COIN_BONUS: 15,

  TYCOON_UPGRADES: [
    {
      key: 'chisel',
      name: 'Cincel afilado',
      icon: '⛏',
      desc: 'Menos clics para abrir una celda vacía (−1 por nivel)',
      maxLevel: 9,
      basePrice: 35,
      priceGrowth: 1.52,
    },
    {
      key: 'quota',
      name: 'Depósito de tinta',
      icon: '🪣',
      desc: '+120 píxeles máximos por recarga (10 min)',
      maxLevel: 6,
      basePrice: 110,
      priceGrowth: 1.75,
      effect: 120,
    },
    {
      key: 'combo',
      name: 'Combo cinético',
      icon: '🔥',
      desc: 'Clics seguidos en la misma celda cuentan extra',
      maxLevel: 4,
      basePrice: 75,
      priceGrowth: 1.6,
      effect: 1,
    },
    {
      key: 'coin_mult',
      name: 'Imán de monedas',
      icon: '🧲',
      desc: '+12% monedas de misiones y recompensas por nivel',
      maxLevel: 5,
      basePrice: 95,
      priceGrowth: 1.68,
      effect: 0.12,
    },
    {
      key: 'passive',
      name: 'Generador idle',
      icon: '⚡',
      desc: 'Monedas pasivas por minuto mientras no pintas',
      maxLevel: 6,
      basePrice: 180,
      priceGrowth: 1.85,
      effect: 3,
    },
    {
      key: 'xp_boost',
      name: 'Mentor pixel',
      icon: '📈',
      desc: '+20% experiencia por nivel',
      maxLevel: 4,
      basePrice: 130,
      priceGrowth: 1.72,
      effect: 0.2,
    },
  ],

  /** XP acumulada necesaria para alcanzar cada nivel (índice = nivel) */
  TYCOON_LEVEL_XP: [0, 40, 100, 190, 310, 470, 680, 950, 1280, 1680, 2150, 2700, 3350, 4100, 5000],

  SHOP_CATEGORIES: [
    {
      id: 'dibujo',
      name: 'Pintura y herramientas',
      icon: '🎨',
      tip: 'Cambia cómo pintas en el lienzo. Algunos son permanentes, otros se gastan al usarlos.',
    },
    {
      id: 'territorio',
      name: 'Territorio',
      icon: '🛡',
      tip: 'Píxeles extra para reclamar zonas protegidas (modal Territorio → modo reclamar).',
    },
    {
      id: 'combate',
      name: 'Combate y asedio',
      icon: '⚔',
      tip: 'Ataca territorios ajenos. Un asedio normal cuesta 75🪙; el token lo evita.',
    },
    {
      id: 'utilidades',
      name: 'Utilidades',
      icon: '🔧',
      tip: 'Mejoras permanentes de interfaz y exploración del mapa.',
    },
    {
      id: 'tycoon',
      name: 'Mejoras Tycoon',
      icon: '⛏',
      tip: 'Invierte monedas para pintar más rápido, ganar XP, combos e ingresos idle.',
    },
    ...shopCatalog.SHOP_CATEGORIES_EXTRA,
  ],

  SHOP: shopCatalog.SHOP,

  MISSIONS: [
    {
      id: 'explorador',
      name: 'Explorador del mapa',
      desc: 'Coloca un píxel cerca de las 4 esquinas lejanas (±5000 del origen)',
      reward: 80,
      type: 'corners',
      corners: [
        { x: 5000, y: 5000 },
        { x: -5000, y: 5000 },
        { x: -5000, y: -5000 },
        { x: 5000, y: -5000 },
      ],
      radius: 30,
    },
    {
      id: 'maraton',
      name: 'Maratonista',
      desc: 'Coloca 300 píxeles en total (progreso acumulado)',
      reward: 120,
      type: 'total_placed',
      target: 300,
    },
    {
      id: 'octantes',
      name: 'Cartógrafo',
      desc: 'Pinta lejos del origen en las 8 direcciones del mapa',
      reward: 100,
      type: 'octants',
      target: 8,
    },
    {
      id: 'constancia',
      name: 'Veterano',
      desc: 'Inicia sesión 5 días consecutivos',
      reward: 150,
      type: 'login_streak',
      target: 5,
    },
    {
      id: 'artesano',
      name: 'Artesano',
      desc: 'Completa un bloque sólido de 10×10 del mismo color',
      reward: 200,
      type: 'solid_block',
      size: 10,
    },
    {
      id: 'conquistador',
      name: 'Conquistador',
      desc: 'Gana un asedio y captura el territorio de otro jugador',
      reward: 250,
      type: 'siege_won',
      target: 1,
    },
    {
      id: 'cincelador',
      name: 'Cincelador',
      desc: 'Realiza 200 clics de cincel en el mapa',
      reward: 90,
      type: 'total_taps',
      target: 200,
    },
    {
      id: 'inversor',
      name: 'Inversor',
      desc: 'Compra tu primera mejora tycoon',
      reward: 60,
      type: 'tycoon_upgrade',
      target: 1,
    },
  ],
};
